apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  namespace: {{ .Values.TargetNamespace}}
  name: kkhpa
spec:
  maxReplicas: 6
  minReplicas: 2
  scaleTargetRef:
    apiVersion: argoproj.io/v1alpha1
    kind: Rollout
    name: kkrollout
  targetCPUUtilizationPercentage: 80