apiVersion: projectcontour.io/v1
kind: HTTPProxy
metadata:
  namespace: {{ .Values.TargetNamespace }}
  name: kkhttpproxy
spec:
  ingressClassName: contour
  virtualhost:
    fqdn: localhost
  routes:
    - conditions:
      - prefix: /
      enableWebsockets: true
      services:
        - name: kkservice
          port: 80
      loadBalancerPolicy:
        strategy: Cookie