apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  namespace: {{ .Values.TargetNamespace}}
  name: kkingress
  annotations:
    #https://docs.ovh.com/sg/en/kubernetes/sticky-session-nginx-ingress/
    nginx.ingress.kubernetes.io/rewrite-target: /
    nginx.ingress.kubernetes.io/affinity: "cookie"
    nginx.ingress.kubernetes.io/session-cookie-name: "stickounet"
    nginx.ingress.kubernetes.io/session-cookie-expires: "172800"
    nginx.ingress.kubernetes.io/session-cookie-max-age: "172800"
spec:
  ingressClassName: nginx
  rules:
  - http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: kkservice
            port:
              number: 80

---
#https://kubernetes.github.io/ingress-nginx/user-guide/nginx-configuration/annotations/#canary
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  namespace: {{ .Values.TargetNamespace}}
  name: kkingress-canary
  annotations:
    nginx.ingress.kubernetes.io/canary: "true"
    nginx.ingress.kubernetes.io/canary-by-header: "x-canary"
    nginx.ingress.kubernetes.io/canary-by-header-value: "true"
spec:
  ingressClassName: nginx
  rules:
  - host: localhost
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: kkservice-canary
            port:
              number: 80
