apiVersion: v1
kind: Namespace
metadata:
  name: {{ .Values.TargetNamespace }}

---

apiVersion: v1
kind: Namespace
metadata:
  name: jaeger

---

apiVersion: v1
kind: Namespace
metadata:
  name: nginx