apiVersion: argoproj.io/v1alpha1
kind: Rollout
metadata:
  namespace: {{ .Values.TargetNamespace}}
  name: kkrollout
  labels:
    app: kkapp
spec:
  strategy:
    canary:
      steps:
      - setWeight: 20
      - pause:
          duration: "10m"
      - setWeight: 40
      - pause:
          duration: "10m"
      - setWeight: 60
      - pause:
          duration: "10m"        
      - setWeight: 80
      - pause:
          duration: "10m"
      - setWeight: 100
      
      canaryService: kkservice-canary
      stableService: kkservice-stable
      trafficRouting:
        trafficRouting:
        nginx:
          stableIngress: kkingress
          additionalIngressAnnotations:
            canary-by-header: x-canary
            canary-by-header-value: "true"
  revisionHistoryLimit: 2
  selector:
    matchLabels:
      app: kkapp
      version: main
  template:
    metadata:
      labels:
        app: kkapp
        version: main
    spec:
      containers:
      - name: kkapp
        image: {{ .Values.Image }}
        imagePullPolicy: Always
        ports:
        - containerPort: 80