apiVersion: v1
kind: Service
metadata:
  namespace: {{ .Values.TargetNamespace }}
  name: kkservice-stable
  labels:
    app: kkapp
spec:
  ports:
  - port: 80
    protocol: TCP
    targetPort: 80
  selector:
    app: kkapp
  type: ClusterIP

---

apiVersion: v1
kind: Service
metadata:
  namespace: {{ .Values.TargetNamespace }}
  name: kkservice-canary
  labels:
    app: kkapp
spec:
  ports:
  - port: 80
    protocol: TCP
    targetPort: 80
  selector:
    app: kkapp
  type: ClusterIP
