{{- if .Values.allInOne.samplingConfig }}
apiVersion: v1
kind: ConfigMap
metadata:
  namespace: {{ quote .Values.namespaceOverride }}
  name: {{ include "jaeger.fullname" . }}-sampling-strategies
  labels:
    {{- include "jaeger.labels" . | nindent 4 }}
    app.kubernetes.io/component: all-in-one
data:
  strategies.json: |-
{{ tpl .Values.allInOne.samplingConfig . | indent 4 }}
{{- end }}
