{{- if .Values.collector.samplingConfig }}
apiVersion: v1
kind: ConfigMap
metadata:
  namespace: {{ quote .Values.namespaceOverride }}
  name: {{ include "jaeger.fullname" . }}-sampling-strategies
  labels:
    {{- include "jaeger.labels" . | nindent 4 }}
    app.kubernetes.io/component: collector
data:
  strategies.json: |-
{{ tpl .Values.collector.samplingConfig . | indent 4 }}
{{- end }}

