apiVersion: v2
name: kalkulator-kredytowy-charts
type: application
version: 0.2.7

dependencies:
- name: ingress-nginx
  version: "4.4.0"
  repository: "https://kubernetes.github.io/ingress-nginx"
- name: jaeger
  version: "0.65.4"
  repository: "file://../jaeger"