Image: "ghcr.io/gitmanik/kk-konkurs:main"
TargetNamespace: "kalkulator"

nginx:
  fullnameOverride: "nginx"
  nodeSelector:
    ingress-ready: "true"

jaeger:
  namespaceOverride: "jaeger"
  provisionDataStore:
    cassandra: false
  allInOne:
    enabled: true
  storage:
    type: none
  agent:
    enabled: false
  collector:
    enabled: false
  query:
    enabled: false