apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: kalkulator
  namespace: argocd
spec:
  destination:
    name: ''
    namespace: ''
    server: 'https://kubernetes.default.svc'
  source:
    path: kalkulator-kredytowy-charts
    repoURL: 'https://github.com/Gitmanik/kk-konkurs'
    targetRevision: HEAD
  project: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: false
    syncOptions:
      - PrunePropagationPolicy=foreground