apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: kalkulator
  namespace: argocd
spec:
  destination:
    name: ''
    namespace: ''
    server: 'https://kubernetes.default.svc'
  source:
    repoURL: 'http://gitmanik.github.io/kk-konkurs'
    targetRevision: "*"
    chart: kalkulator-kredytowy-charts
  project: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: false
    syncOptions:
      - PrunePropagationPolicy=foreground