name: Automatyzacja budowania, instalacji, testowania i skanowania aplikacji

on:
  push:
    branches: ['main']

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}

jobs:
  doitall:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Sonar
        uses: ./.github/workflows/sonar.yml
      - name: Helm Chart
        uses: ./.github/workflows/push-chart.yml
      - name: Docker
        uses: ./.github/workflows/push-docker.yml